sonar.projectKey=yitzhaq_mulberry-main
sonar.organization=yitzhaq
sonar.host.url=https://sonarcloud.io

sonar.sources=Sources_Common,Linux,Plug-ins,Win32,MacOS,Libraries/CICalendar,Libraries/vCard,Libraries/XMLLib
sonar.sourceEncoding=UTF-8

sonar.cpp.file.suffixes=.cc,.cpp,.cxx,.c++,.hh,.hpp,.hxx,.h++,.ipp
sonar.python.version=3

sonar.exclusions=\
  Libraries/JX/**,\
  Libraries/open-powerplant/**,\
  Libraries/MoreFiles/**,\
  Libraries/MoreFilesX/**,\
  Libraries/vendor/**,\
  Libraries/vzic/**,\
  Libraries/include/**,\
  Sources_Common/HTTP/HTTPClient/CHTTPRequestResponse.cpp,\
  Linux/Sources/Support/CMailcapMap.cpp,\
  Linux/Sources/Support/CMIMETypesMap.cpp,\
  Linux/Sources/Support/Network/CUnixINET.cpp,\
  Plug-ins/vCardAdbkIO/sources/CVCard.cpp,\
  Sources_Common/Mail/Attachments/CMIMEContent.cpp,\
  Sources_Common/Mail/Control/CPasswordManagerKeyring.cpp,\
  Sources_Common/Mail/Mailbox/CMboxList.cpp,\
  Sources_Common/Mail/Message/CEnvelope.cpp,\
  Sources_Common/Offline/Recording/CAdbkAction.cpp,\
  Sources_Common/Offline/Recording/CCalendarAction.cpp,\
  Sources_Common/Offline/Recording/CMailAction.cpp
