#!/bin/sh

./makeresxpm < icons.rc > xpms.res
./makeresxpminit < icons.rc > xpms.cpp
#./makeresxpm < icons_unix.rc >> xpms.res
#./makeresxpminit < icons_unix.rc >> xpms.cpp

./makeresico < icons_ico.rc > icos.res
./makeresicoinit < icons_ico.rc > icos.cpp
./makeresico < icons_ico_unix.rc >> icos.res
./makeresicoinit < icons_ico_unix.rc >> icos.cpp

./makeresstring < Mulberrytxt.rc > string.res
./makeresstringinit < Mulberrytxt.rc > stringinit.cpp
./makeresstring < MulberryUnix.rc >> string.res
./makeresstringinit < MulberryUnix.rc >> stringinit.cpp
./makeresstring < MulberryTips.rc2 >> string.res
./makeresstringinit < MulberryTips.rc2 >> stringinit.cpp
