name: "MegaLinter"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: Analyze (cppcheck)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0

    - name: MegaLinter
      uses: oxsecurity/megalinter/flavors/c_cpp@v9
      env:
        VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload reports
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: megalinter-reports
        include-hidden-files: "true"
        path: |
          megalinter-reports/
          mega-linter.log
